# Puerto de la API REST
server.port=8080

# Conexión a PostgreSQL (reemplaza 'aula_impulso_db', 'tu_usuario' y 'tu_contraseña')
spring.datasource.url=jdbc:postgresql://localhost:5432/aula_impulso_db
spring.datasource.username=postgres
spring.datasource.password=76179360
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect